### PR TITLE
Build better production bundles

### PR DESCRIPTION
**Pull request by vwong**
Added/configured:
- production build of React
- strip non-english locales for moment.js
- uglify
- gzip

The result is:
- bundle.js went from 2.3MB to 163kB gzip'ed
- style.css went from 36KB to to 5.3kB gzip'ed

### CODE REVIEW

**Comment by snobear** [comment]
Just an FYI I was reading in the [express js docs on compression](https://expressjs.com/en/advanced/best-practice-performance.html):

> For a high-traffic website in production, the best way to put compression in place is to implement it at a reverse proxy level (see Use a reverse proxy). In that case, you do not need to use compression middleware. For details on enabling gzip compression in Nginx, see Module ngx_http_gzip_module in the Nginx documentation.

i.e. if you've got nginx or another web server in front of your app, then enable `gzip` there instead of in express.

**Comment by vwong** [comment]
Yes, you're totally right.  I was just trying to keep it simple.

I would also like to split the config files, but wanted to keep the diff sufficiently small to make it manageable.

Note also that the JSON payloads  for a long running app (big assumption!), can dominate the total network activity. In that case, the mere 2 static assets above might just disappear in the wash.

**Comment by snobear** [comment]
Cool just thought I'd mention it after I did a little research on the compression package you added. That said I think it's a good addition. 

Also the devtool change in the webpack configure from eval to source map made a HUGE impact on reducing the size of the bundle.  I don't know the difference in the different options for that, but the app works either way so that's a nice change. My app that's based on 3ree was almost 4MB in size and that change brought it down to 1MB.

**Comment by GordyD** [comment]
Thank you for this PR @vwong. The introduction of UglifyJS and use of compression is great for demonstrating to people, with minimal set-up to how the development bundle can shrink ~15x. Thank you for this change!

Whilst I would tend to use nginx to handle compression of responses, as @snobear pointed out, in a production environment I think the simplicity of this for demo purposes is great, and a good addition.

Merging!

**Pull request merged**
