### PR TITLE
Add script for creating a new database

### PR DESCRIPTION
**Pull request by GordyD**
WIP

### CODE REVIEW

**Comment by bigethan** [comment]
I might be reading this wrong, but running this script would drop an existing `pulses` db, no?

**Comment by GordyD** [comment]
Yea, it would. I suppose its purpose is two fold:
- to create a DB and the tables needed if not present
- to recreate DB and the tables afresh if currently is present (a reset)

I could drop point 2 and focus on just ensuring that the required elements are present (the database, and the tables).

**Comment by franklinjavier** [comment]
+1

**Comment by GordyD** [comment]
I've updated the script so that it is now non-destructive, it only creates what is missing.

**Comment by franklinjavier** [comment]
:beers:

**Pull request merged**
