### PR TITLE
extend config file

### PR DESCRIPTION
**Pull request by pcanterini**
Just a suggestion, feel free to close the PR :smile:

### CODE REVIEW

**Comment by pcanterini** [comment]
On that note, the config file could probably be in a different location and have support for multiple envs too. Just some food for thought.

**Comment by GordyD** [comment]
Hey. 

This is certainly an area that needs improvement, so thank you for bringing this up and submmiting a PR. 

I would suggest using the [config](https://github.com/lorenwest/node-config) module from NPM - it caters for configurations for multiple environments (plus local overwrites) and has good community support plus documentation.

If you're cool updating the PR to use this module, or a similar appraoch, I'd be happy to merge in :)

**Comment by pcanterini** [comment]
I like the config module approach, I'll look into it. Thanks

**Comment by pcanterini** [comment]
It doesn't look like node-config is working properly with node 4.x yet but switching to 0.12 fixed the issue (I'll report it tomorrow on their project, I've seen some similar issues lately on v4.x and El Capitan with other modules).

Let me know if you have some feedback and I'll update the README file after that.

**Comment by pcanterini** [comment]
Looks like webpack and config are not playing well with each other. 
Might need some more investigating.

Currently getting:

``` bash
$ npm run build-prod

> pulse@0.0.2 build-prod /Users/pcanterini/projects/3ree
> webpack

Hash: 245e2f524b26e8855f45
Version: webpack 1.9.13
Time: 3268ms
   [0] multi main 28 bytes {0} [built]
    + 593 hidden modules

WARNING in ./~/config/lib/config.js
Critical dependencies:
834:21-42 the request of a dependency is an expression
860:21-42 the request of a dependency is an expression
 @ ./~/config/lib/config.js 834:21-42 860:21-42

WARNING in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'iced-coffee-script' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 863:13-42

WARNING in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'coffee-script' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 852:17-41

WARNING in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'js-yaml' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 925:15-33

WARNING in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'yaml' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 930:28-43

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'fs' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 20:17-30

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'json5' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 956:14-30

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'hjson' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 964:14-30

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'toml' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 972:13-28

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'cson' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 979:13-28

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'properties' in /Users/pcanterini/projects/3ree/node_modules/config/lib
 @ ./~/config/lib/config.js 990:16-37
```

**Comment by GordyD** [comment]
Thanks for the contribution. 

I don't think you can use `config` on the client side as it is not a universal module, hence the errors during Webpack compilation. I am not 100% on this though, but I suspect this is the case. We may have to drop the use of `config` in `universal/actions/PulseActions.js`. 

As for the issues around `config` and Node 4.x, can you show me what you're seeing?

**Comment by pcanterini** [comment]
Yep, you are right.

The other issue was related to node-gyp rebuild errors, I'm not getting them after a reboot :disappointed:

**Comment by GordyD** [comment]
Just been checking out the PR (sorry for the slow turnaround) and all is well running on Node 0.12.7, but after switching to 4.0.0 I get a seg fault when firing up the server. It seems like a number of parts of this repo are at odd with working Node 4.0.0 and I'll have to investigate further. 

I feel it might be best set Node 0.12.7 as the expected runtime for the time being, until I have validated behaviour with Node >4. What do you think?

**Comment by pcanterini** [comment]
I think that's a good approach. As an alternative we may try upgrading the dependency packages to see if the issues were addressed to work with node 4.x or higher.

**Comment by pcanterini** [comment]
There were a couple of breaking changes and I don't have time to review them now so I'm closing the PR and revisiting this later this week, if the changes are still needed by then.

**Comment by GordyD** [comment]
Ok sure thing. I have pulled your branch into a working branch for the basis of my own investigation which will either result in:
- advising on using Node 0.12.7
- isolating problem NPM modules and upgrading so that Node 4.0.0+ is ok.

**Pull request closed without merging**
